### ISSUE TITLE
Page Stats => où stocker les infos ?

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#33]
si la page de questions statistiques n'est pas prête, et qu'on colique sur "stats" dans la barre d'avancement, il faut soit un message dans la page de stats disant qu'elle est hors fonction, et qu'il suffit de cliquer pour arriver aux résultats, soit arriver aux résultats sans explications (ce qui est moins élégant).

**Comment by danielsum** [comment]
J'ai rajouté la découpe de la page => reste à savoir où stocker les infos

**Comment by JPPinon** [comment]
j'ai répondu par email à la question où et quelles info stocker
