### ISSUE TITLE
page de résultats

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#37]
Il faudrait rafraîchir les traductions. L'expression "Les candidats qui partagent le plus mes convictions sont:" est traduite depuis longtemps, me semble-t-il. Or cela n'apparaît pas traduit dans la version NL.
Plus fondamentalement: dans le commune de Tielt, on annonce au début 8 candidats et on montre deux résultats, tous deux à 100%. Pas encore présentable...
Le noms de candidats devraient être cliquables (vers PolDir).

**Comment by olivier5741** [comment]
Seems ok in prod
