### ISSUE TITLE
écran 3: afficher tous les candidats de la commune

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#44]
J'appelle ici "écran 3" l'écran qui s'affiche lorsqu'il y a moins de 6 candidats répondants dans la commune.
Nouveau titre : Parmi les candidats que NousCitoyens a réussi à joindre, seul xxx ont répondu au questionnaire du GPS électoral
Le message  : 
_Le nombre de candidats participants dans la commune est encore insuffisant pour actionner le comparateur du GPS électoral. Tu pourrais réessayer après le 10 octobre. En cliquant sur le nom d'un candidat, tu ouvres son profil. L'onglet "Opinions" te donne ses réponses au questionnaire._

Ensuite, fournir la liste des candidats localisés dans la commune, en distinguant 2 catégories :
•	ceux qui ont répondu  (cliquables). 
•	ceux qui n’ont pas répondu au questionnaire, mais dont le « level of completeness » est >12%  (noms cliquables)

Les noms cliquables dirigent vers le profil du politicien dans PoliticiansOnline, dans la même langue que l’écran de départ.
(ASAP) En footer, le bouton « demander à un ami candidat de participer ».

[M44-180929-communique-de-presse.docx](https://github.com/wecitizens/electoral-gps-frontend/files/2432034/M44-180929-communique-de-presse.docx)

**Comment by olivier5741** [comment]
We need the list of **all** candidates ... Where can I find this ? Online, database ? @JPPinon

**Comment by JPPinon** [comment]
All candidates means:  the candidate (individual or party) is registered as candidate for this municipality: [politician_election/district] = code BExxxx
This filter is not available in the frontend nor backend of PolDir. It has to be taken in MySQL.
