### ISSUE TITLE
installer le certificat https

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#47]
L'hébergeur des sites de WeCitizens est : M. Saad Saad; 0497 455 841; saad@saad.be
Il a installé le certificat pour PoliticiansOnline:  https://directory.wecitizens.be
Il faut aussi sécuriser   gps.wecitizens.be

**Comment by danielsum** [comment]
Done

**Comment by JPPinon** [comment]
@danielsum Il reste à forcer le passage par https
