### ISSUE TITLE
corriger la formule de matching

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#48]
Nous voudrions inclure dans le GPS électoral les candidats qui n'ont pas répondu à toutes les questions qui leur ont été soumises. Le fichier ci-annexé montre les modifications par rapport à la formule de matching initiale.

[Q22-Matching_methodology.docx](https://github.com/wecitizens/electoral-gps-frontend/files/2432024/Q22-Matching_methodology.docx)

**Comment by olivier5741** [comment]
Done in test through https://github.com/wecitizens/electoral-gps-frontend/commit/567c6d45fcc08e83b26ce12286baa3f1ee8cc8d6

TODO : refactoring and integrate to app

**Comment by olivier5741** [comment]
Refactoring done, much more friendly now :). I won't the time to do it tonight if someone is motivated ;).

Merge https://github.com/wecitizens/electoral-gps-frontend/blob/develop/utils/matching_test/matching_test.js with https://github.com/wecitizens/electoral-gps-frontend/blob/develop/src/store/gps/match.js#L37

Code mismatch at several places ....

**Comment by olivier5741** [comment]
ok in local, Daniel is deploying to demo soon

**Comment by Damiendv** [comment]
J'ai répondu à toutes les questions du GPS hier soir pour 1050-Ixelles. J'ai eu comme premier candidat proposé "Roland Janampa Ramos" avec 100% de matching. Quand j'ai été voir ses opinions sur son profil, j'ai vu qu'il n'avait répondu à aucune question du GPS communale. Je ne comprends donc pas comment il peut avoir 100%. 

Peut-être un bug dans la formule?

**Comment by olivier5741** [comment]
En prod ou en démo ?

**Comment by olivier5741** [comment]
Salut Damien,

Va sur https://gps.wecitizens.be
fait CTRL-F5 (rafraîchit le cache du browser)
Prend 1050
Répond toujours pas d'accord.

J'arrive sur 
![image](https://user-images.githubusercontent.com/3897291/46417924-f05d4b80-c72a-11e8-88bb-1acfc53b292c.png)

![image](https://user-images.githubusercontent.com/3897291/46417966-0bc85680-c72b-11e8-9ca3-b7ded2c8c37b.png)

Tu sais tester ;)

**Comment by Damiendv** [comment]
J'ai fais comme toi mais en répondant différemment et au hasard. Ca marche.

C'est donc un pb. avec le Cache?

Merci!
_______________________

*Damien De Vroey*

Strategy consultant | Economist |
Political advisor at the Belgian parliament

M: +32(0)473.99.72.06

<http://www.linkedin.com/in/damien-de-vroey>
