### ISSUE TITLE
Duplicate info in election API request

### ISSUE THREAD

**Issue by olivier5741** [wecitizens/electoral-gps-frontend#49]
@danielsum, was it to ease the process that there is duplicate info in election json ? The party and order of the candidates are also added to the the candidates info.

![image](https://user-images.githubusercontent.com/3897291/46266535-12d74500-c530-11e8-8f60-3173efd1ed68.png)

**Comment by danielsum** [comment]
Yes it is.

It simplify the query because it’s needed when you call the election.

Dan

--
Daniel Sum

**Comment by olivier5741** [comment]
I would then rename 

* `order` to `electoral_list_order`
* `list` to `electoral_list_key`, put the key instead of the french name  and play with translations (not the case right now with `list`)

**Comment by danielsum** [comment]
This would be more compute consuming => I will keep it like that as the order like that will take less programmation KISS
