### ISSUE TITLE
questionnaire GPS

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#50]
Le GPS représente les même questions, déjà répondues. Après la question 11 il me fait passer à la question 3, etc. C'est un carroussel sans fin !

**Comment by Damiendv** [comment]
Je n'ai pas ce problème la (sur 1050-Ixelles) mais, par contre, le GPS ne progresse plus après la question "Les autorités doivent mener une politique active pour assurer aux personnes LGBTQI+ une meilleure reconnaissance sociale.". Je sélectionne une bulle dans laquelle s'affiche le "V" qui clignote mais je ne passe pas à la prochaine question. La flèche ">" (prochaine question) ne réagit pas non-plus. La flèche "<" (précédente question) fonctionne bien. Le bouton "voir les résultats" fonctionne

**Comment by Damiendv** [comment]
Si, depuis le GPS, je clique sur "résultats" dans les étapes en faut, ils s'affichent tout de suite sans passer par les statistiques

**Comment by olivier5741** [comment]
For brussels (don't know how to test the other GPS) goes until the end but when the survey ends you have to click to results. Ok in local, daniel is deploying to demo soon. 

" when the survey ends you have to click to results" -> for 10/10
