### ISSUE TITLE
(ASAP) icône loader

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#53]
lorsqu'il y a un temps d'attente, il convient d'afficher une icône indiquant que l'appareil est actif. C'est surtout vrai lorsqu'on attend les résultats du comparateur. Mais je crains qu'il le faille aussi lorsque l'utilisateur a encodé son code postal.

**Comment by olivier5741** [comment]
Voir avec Daniel, j'ai l'impression que depuis que l'API fait appel à la db
c'est plus lent ... On n'est plus full static et on est sur des serveurs
webs et dbs basiques ... Peut-être qu'on devrait plus regarder de ce côté
là plutôt que de mettre une icône d'attente ...

**Comment by olivier5741** [comment]
Ok in prod
