### ISSUE TITLE
(ASAP) Number of questions for each GPS

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#54]
We would like to reduce the number of questions for each GPS.
Is it enough to order this to Banlieues (who will change the parameters in PolDir)?
Is it OK to continue having a different number of questions in each GPS?

**Comment by olivier5741** [comment]
done through
https://docs.google.com/spreadsheets/d/1bPQsDi-vsT4PCuJpPysR1bm3AqXrTCM1NNJyGIIebOc/edit#gid=1733549953
('Surveys' sheet) then ask a dev to regenerate and publish. I don't see the
link with Banlieues, to you want to change the politician form ?
