### ISSUE TITLE
Délai "Mon code postal"

### ISSUE THREAD

**Issue by Damiendv** [wecitizens/electoral-gps-frontend#57]
Sur la page "Mon Code Postal", lorsque je rentre la commune 1050-Ixelles, il faut 10 secondes avant que le bouton "c'est parti" apparaisse. En attendant, l'utilisateur lambda pense qu'il y a un bug et abandonne. S'il n'est pas possible de racourcir le temps de calcul, il faudrait au moins une icone ou barre de chargement.

**Comment by olivier5741** [comment]
@danielsum, tu sais regarder la config de Amazon pour que l'API / db soit always on ...
