### ISSUE TITLE
(Urgent) Matching methodology

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#71]
Le document publié: 
http://www.wecitizens.be/docs-en/Q22-Matching_methodology.pdf
reflète-t-il bien correctement le calcul de matching de notre GPS actuel ?

**Comment by olivier5741** [comment]
"When two or more candidates achieve the same score, they are ranked according to the
level of completeness their profile in PoliticiansOnline." -> not yet impemented

"When a candidate does not answer all questions" -> "When the end user answered questions not answered by the candidate" (la pénalité "se met en marche" pour question répondue, celle du matching, et pas toutes les questions du questionnaire)
