### ISSUE TITLE
Rediriger automatiquement de l'URL http >> httpS

### ISSUE THREAD

**Issue by Damiendv** [wecitizens/electoral-gps-frontend#76]
Ce matin à 11:50, le site n'est plus httpS (il l'était avant, il me semble)

![image](https://user-images.githubusercontent.com/43785103/46661685-f2575c80-cbb9-11e8-9a8e-c4e833e3cdc7.png)

**Comment by danielsum** [comment]
@Damiendv  => corrigé => c'était déjà corriger mais ça a dû être écraser par erreur par Olivier

**Comment by olivier5741** [comment]
Sorry :)
