### ISSUE TITLE
Candidat qui a répondu à des questions mais reste grisé ou vice-versa

### ISSUE THREAD

**Issue by Damiendv** [wecitizens/electoral-gps-frontend#77]
Sur Ixelles, je recois le message qu'il y a moins de 6 candidats. Le profile de la Bourgemestre actuelle, Dominique Defourny, est grisé. Quand je clique sur son profile, je vois néanmoins qu'elle a répondu à plein de questions communales le 29/09/2018. Est-ce normal? Nous avions décidé de quand même intégrer les gens qui avaient répondus à quelques questions. Quand est-ce que celà sera opérationnel? Je pense que ce changement est le plus urgent car, si on augmente le nombre de candidats considérés au delà du seuil de 6, on rend le GPS utile pour beaucoup plus de communes. Merci!

![image](https://user-images.githubusercontent.com/43785103/46683687-1bdfaa80-cbf1-11e8-8f1f-e64bf8e4dec9.png)

![image](https://user-images.githubusercontent.com/43785103/46683708-269a3f80-cbf1-11e8-8a9d-cf8df0bda81f.png)

@danielsum @olivier5741

**Comment by Damiendv** [comment]
pour info, elle apparait dans les résultats. C'est donc dans les critères de lancement du GPS:

![image](https://user-images.githubusercontent.com/43785103/46684238-82b19380-cbf2-11e8-98a2-18314e29daac.png)

**Comment by olivier5741** [comment]
**Dufourny** pas Defourny ...

**Comment by olivier5741** [comment]
Here is the data `"total_received": 0` : 

```json
    {
      "completeness": 70,
      "full_name": "Dominique Dufourny",
      "has_answered": 0,
      "img": "http://directory.wecitizens.be/assets/media/vignette_user/46a5ef21bb7da34e8f42ec89ee204fb9.jpg",
      "key": "be_politician_3146",
      "list": "Ixelles - Liste de la Bourgmestre",
      "order": 1,
      "politician_id": 3146,
      "status": null,
      "total_questions": 25,
      "total_received": 0
    }
```

**Comment by olivier5741** [comment]
`SELECT * FROM wecitizens_poldir.opinions_answers where id_politician = 3146` -> opinion_total_received is 0. Data quality issue !! 

The query needs to be updated in https://github.com/wecitizens/electoral-gps-frontend/blob/develop/api/routes/index.js#L132, use something as `sum(case when opinion_answer > 0 then 1 else 0 end)` (gives too much result -> group by must be changed or filter must be refined).

I don't have the time to do it ...

**Comment by danielsum** [comment]
=> as explained by Olivier => Data quality issue 

=> I put a quick fix by filtering politician that have answered (but that need to be adjusted)

**Comment by Damiendv** [comment]
Merci Daniel, j'ai testé et malheureusement l'outil charge/tourne pendant
plus d'une minute (je n'ai pas attendu plus longtemps, ça pourrait durer
beaucoup plus) une fois qu'on a mis le numéro de code postal et appuyé sur
le bouton pour continuer. Je pense que la charge de calcul est trop
importante.

 Ne serait il pas possible de calculer un indicateur binaire
d'inclusion/exclusion du candidat qu'une fois par jour, après la synchro
des banques de données ? Que cet indicateur soit stocké dans la DB du GPS
(je suppose qu'il y en a une) et utilisé de la.

C'est une suggestion, vous êtes évidemment plus compétents pour savoir quoi
faire.

Merci !

**Comment by Damiendv** [comment]
Aye. Je comprends.Merci

en attendant, il serait peut-être mieux de rétablir l'état précédent pour
que les gens puissent au moins avancer après avoir entré leur code postal.
L'événement Facebook commence à tourner et je suppose que les gens vont sur
le GPS.

**Comment by JPPinon** [comment]
Je fais le GPS pour la commune de Ans. La liste "insufficient candidates" indique 3 répondants (affichés en noir). Je clique sur Magali Rizzi. Or elle n'a répondu à aucune question...

**Comment by olivier5741** [comment]
"Je fais le GPS pour la commune de Ans. La liste "insufficient candidates" indique 3 répondants (affichés en noir). Je clique sur Magali Rizzi. Or elle n'a répondu à aucune question...", Ok in demo (correction of the query) but not deployed to prod. @danielsum , when you have the time ;)

**Comment by olivier5741** [comment]
Ok in prod
