### ISSUE TITLE
(re)direction vers la bonne langue

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#79]
1) Quand on clique sur : gps.wecitizens.be , apparemment tout le monde arrive sur la page FR.
Il faudrait adapter cela d'urgence.
Soit l'application détecte la langue du 'device", Soit on donne la possibilité d'utiliser un lien du genre:
gps.wecitizens.be/nl

2) de nombreux flamands me disent que chez eux le GPS donne seulement les communes en français.

**Comment by olivier5741** [comment]
Seems ok in prod and demo. Redirection to `#/fr` does not work yet (en and nl ok) but it's part of another issue
