### ISSUE TITLE
District - Postcode issue - 9120, 8790, 3390 

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#81]
On me signale une erreur dans la table des codes postaux du GPS.
J’ai mis en jaune les lignes (90 et 571) du tableau  B-districts, dans Dropbox. Elles concernent:

BE9120 | BEVEREN-WAAS
BE8790 | WAREGEM

**Comment by olivier5741** [comment]
@JPPinon, can you tell me in the issue exactly what should be replaced by what. Thanks ;)

**Comment by JPPinon** [comment]
@olivier5741 
II y a une erreur : 9120 ne répond pas et Beveren répond 8791 Beveren, ce qui correspond à une entité de la commune de Waregem (8790).
Il faut donc ajouter 9120.
Supprimer 8791
3390 Tielt-Winge s'y trouve deux fois
D'une façon général, le GPS devrait correspondre à B-district; colonne F; lignes 32 et ss
[B-Districts.xlsx](https://github.com/wecitizens/electoral-gps-frontend/files/2468416/B-Districts.xlsx)
