### ISSUE TITLE
Candidat qui a répondu à toutes les questions, et n'apparaît pas dans la liste "insufficient candidates"

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#82]
@danielsum et @olivier5741 
Aujourd'hui mercredi 16h29, j'ai fait le test sur Ixelles.
Boris De Kock n'apparaît pas dans la liste.
Or il a répondu à toutes les questions lundi.
Avant lundi, il avait déjà répondu à une question (la n°4)

**Comment by olivier5741** [comment]
Prod and demo versions are increasing in quality. I also spotted this data missing between prod and demo (on Ixelles)

Boris De Kock is present in http://demo-api.wecitizens.be/v1/vote/election/2018_be_municipal/district/be_1050.json but not in https://api.wecitizens.be/v1/vote/election/2018_be_municipal/district/be_1050.json

**Comment by olivier5741** [comment]
Ok in prod and demo
