### ISSUE TITLE
Commentaire "insufficient candidate"

### ISSUE THREAD

**Issue by Damiendv** [wecitizens/electoral-gps-frontend#83]
Le commentaire "insufficient candidate" n'est plus adéquat puisque nous sommes maintenant le 10/10.

Je propose de le changer de:

_"Le nombre de candidats participants dans la commune est encore insuffisant pour actionner le comparateur du GPS électoral. Tu pourrais réessayer après le 10 octobre. En cliquant sur le nom d'un candidat, tu ouvres son profil. Les premiers noms (affichés en noir) ont répondu à des questions. L'onglet "Opinions" (dans leur profil) affiche leurs réponses."_

à 

>> "Le nombre de candidats participants dans la commune est encore insuffisant pour actionner le comparateur du GPS électoral. Reviens le 13 octobre, la veille des élections pour réessayer. Tu peux néanmoins faire le test, si tu le souhaites, en cliquant sur l'étape "2. Question", ci dessus. Aussi, tu peux déjà ouvrir le profil du candidat en cliquant sur son nom. Les premiers noms (affichés en noir) ont répondu à des questions. L'onglet "Opinions" (dans leur profil) affiche leurs réponses."

EN >> "The number of participating candidates in your municipality is still insufficient to run the matching function. Come back on the 13th of October, on the eve of the elections, to try again. You can anyways already do the test by clicking on step "2. Questions", here abore. You can also already open the profile of candidates by clicking on their name. The first names (displayed in black) have answered some questions. The "Opinions" tab (in their profile) gives you their answers."

@JPPinon ; peux-tu stp faire la version NL? Merci

Merci! @olivier5741 @danielsum

**Comment by olivier5741** [comment]
Ok in prod and demo
