### ISSUE TITLE
https://gps.wecitizens.be/#/fr redirects to empty screen

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#86]
Un utilisateur m'a tél parce qu'un ouvrant l'adresse gps.wecitizens.be, il tombait sur une page blanche.
De fait cela se reproduit chez moi quand je fais le lien que tu viens de me donner:
![image](https://user-images.githubusercontent.com/43548775/46763671-c1227d80-ccda-11e8-9a19-9287545429a4.png)

**Comment by olivier5741** [comment]
https://gps.wecitizens.be/#/en
https://gps.wecitizens.be/#/nl

are ok (prod and demo)

only https://gps.wecitizens.be/#/fr does not work
