### ISSUE TITLE
Newsletter popup - improve translation

### ISSUE THREAD

**Issue by Damiendv** [wecitizens/electoral-gps-frontend#88]
il faut remplacer le ["?] par un point. Merci

![image](https://user-images.githubusercontent.com/43785103/46792973-ddf39b00-cd44-11e8-9a37-1fba713b502e.png)

**Comment by JPPinon** [comment]
@danielsum 
La traduction NL est imbuvable. Je constate que ma traduction (donnée antérieurement) n'est pas arrivée au bon endroit. J'ai corrigé sur le "translation file".

**Comment by olivier5741** [comment]
![screenshot_20181012-232043](https://user-images.githubusercontent.com/3897291/46894652-8274fa80-ce75-11e8-892b-33df6fe97d86.png), from demo, seems ok to me ...
