### ISSUE TITLE
calcul du matching

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#89]
@olivier5741 @danielsum 
Le jour des élections je fais le constat suivants:
Je répond sur Uccle, aux deux premières questions, "tout à fait d'accord":
52. Il faut fusionner les communes de Bruxelles.
23. Les fonctionnaires peuvent porter des signes révélant leur appartenance religieuse et / ou philosophique, même s'ils sont en contact avec le public.

Ensuite, je clique sur résultats, dans la barre d'avancement.
Henry Marchal, qui a répondu, le 7 octobre, à tout le questionnaire, ne figure pas dans les résultats. Il aurait dû s'afficher avec un score de 100%.

Charles Bogaerts obtient 66%. Il a répondu, pour ces deux questions:
52. plutôt d'accord
23. pas du tout d'accord.
D'après ma formule, il doit avoir un score de 44%.
Les gens vont faire des vérifications a posteriori. Il faut corriger ceci d'urgence.

**Comment by olivier5741** [comment]
Pour le matching, il n'y a que la question 52 ; la réponse de l'autre question n'est pas connue (question_23)

![image](https://user-images.githubusercontent.com/3897291/46921167-2b4b6300-cff8-11e8-9458-88165653d032.png)

**Comment by olivier5741** [comment]
La réponse à la question se trouve dans les data : http://demo-api.wecitizens.be/v1/gps/answer/segment/2018_be_municipal_be_1180_candidate.json

**Comment by olivier5741** [comment]
J'ai trouvé, mismatch entre `fully_agree` et `strongly_agree` ; la réponse n'est pas considérée comme trouvée .... 

![image](https://user-images.githubusercontent.com/3897291/46921332-4ae38b00-cffa-11e8-8f52-4e856e1257c9.png)

**Comment by olivier5741** [comment]
Should be 27% in fact : https://www.wolframalpha.com/input/?i=1-sqrt%5B25%5E2%2B100%5E2%5D%2Fsqrt%5B100%5E2%2B100%5E2%5D

Ok in local. @danielsum, can you push in demo and prod when you have the time ;).
https://github.com/wecitizens/electoral-gps-frontend/commit/58ca1daeadcad6f339c59ef768608edf46dbe658

The matching correctness was the most important stuff and we failed :/

**Comment by olivier5741** [comment]
Issue present since 12 september : https://github.com/wecitizens/electoral-gps-frontend/commit/e33b7c3372bcf72737195d8850da315eb2c7f962#diff-b82f8f8fd7f2f7a54a96941ad2876a61 (the moment I didn't use fake data anymore). So bug was present since implementation and never spotted ...

Impact : when the answer of a politician (or electoral list) was 'strongly_agree' or 'strongly_disagree' it is not taken into account : the algorithm takes it as a missing answer.

**Comment by JPPinon** [comment]
Le résultat du matching est encore complètement à côté de la plaque. 
@danielsum  : A titre conservatoire peux-tu désactiver le gps.wecitizens.be en affichant une page dont j'inscris le contenu dans la translation file.
Voici le résultat de mon test:
 

Sur Uccle |   |   |   |   |  
-- | -- | -- | -- | -- | --
  | n° questionnaire | sujet | n° PolDir | Ma réponse | Bogaerts | Marchal
  | 1/27 | fusion communes | 52 | 1 | 2 | 1
  |   | 23/port de signes   religieux | 23 | 1 | 5 | 1
  | 3/27 | moins d'impôt | 4 | 3 | 2 | 1
  | 4/27 | pétition 0,5% | 101 | 4 | 5 | 2
  |   |   |   |   |   |  
  |   |   |   |   |   |  
  |   |   |   |   |   |  
  |   |   |   |   |   |  
  | Score attendu |   |   | 39% | 71%
  | Score observé |   |   | 66% | 41%

**Comment by olivier5741** [comment]
Ce que j'ai modifié en local n'a pas été déployé, ni sur démo ni en prod ...

**Comment by olivier5741** [comment]
@danielsum, il faut forcer le restart de l'api ...

en demo

![image](https://user-images.githubusercontent.com/3897291/47035687-edc31300-d17a-11e8-8496-29dd32c4eafc.png)

en local

![image](https://user-images.githubusercontent.com/3897291/47035752-13501c80-d17b-11e8-8521-5bacd1423d18.png)

**Comment by JPPinon** [comment]
@olivier5741 @danielsum : J'ai testé demo et le matching a l'air de fonctionner. Sauf un point qui n'est pas conforme à la méthodologie publiée ( http://www.wecitizens.be/docs-en/Q22-Matching_methodology.pdf ). Au bas du premier tableau on y dit: 
(1) When a voter clicks on “I give no opinion”, it has the same effect as “no answer” (=
skipping that question).

**Comment by olivier5741** [comment]
Demo and prod ok for the issue :). I'll move last JPP question to new issue. Thanks @danielsum ;)

**Comment by olivier5741** [comment]
See https://github.com/wecitizens/electoral-gps-frontend/issues/90
