### ISSUE TITLE
Make the app beautiful

### ISSUE THREAD

**Issue by olivier5741** [wecitizens/electoral-gps-frontend#9]
Do we go for bootstrap (4?) ? Sass (is newspaper website branding required ?) ? Any website samples ?

**Comment by olivier5741** [comment]
Foundation (css framework) seems interesting too : see https://www.obama.org/ (one of the showcases).
 
Integration to nuxt (https://zendev.com/2018/05/04/adding-scss-libraries-like-foundation-to-nuxt.html in https://github.com/kball/nuxt-foundation-demo)

**Comment by thomasvds** [comment]
I already included element-ui from the start as it is in my opnion much more powerful than Bootstrap and Foundation: http://element.eleme.io/#/en-US/component/button

This has been included as a plugin in the app and so all components are available :)

**Comment by olivier5741** [comment]
Daniel told me sooner today that we had element-ui. Forgot about it ;).

**Comment by danielsum** [comment]
@olivier5741  => yes we use Element UI I don't think that Bootstrap will be needed => I have added Tailwind in complement to Element UI for the usefull Bootstrap helpers has (with Flexbox, margin helper etc)

=> for the design himself still in discussion :/ 

I think that I will ask to our designer to choose a theme style

**Comment by olivier5741** [comment]
Additionnal info : Banlieues is using bootstrap v4 for politician profile (the GPS app will link to it for additionnal politician info) and it looks good :).

**Comment by olivier5741** [comment]
Will see how to match component or adhering to global style standards should do it :).
